INSERT INTO `usuarios` (`nombres`, `cargo`, `jefe`, `usuario`, `contrasena`) VALUES
  ('JUAN DAVID LOPEZ ESPINEL', 'TÉCNICO ELECTRICISTA', 'jimena', 'juan.lopez', MD5('pass')),
  ('ANGEL ANDRES SANCHEZ AGUIRRE', 'TÉCNICO ELECTRICISTA', 'jimena', 'angel.sanchez', MD5('pass')),
  ('DIEGO ALEXANDER ZORRO ZORRO', 'PLANILLERO NOTIFICADOR', 'jimena', 'diego.zorro', MD5('pass')),
  ('ELVER MIGUEL RUBIANO ACEVEDO', 'PLANILLERO NOTIFICADOR', 'jimena', 'elver.rubiano', MD5('pass')),
  ('LINA ROCIO BECERRA CHAPARRO', 'COORDINADORA ZONA', 'jimena', 'chaparro.lina', MD5('pass')),
  ('JULIO ALEXANDER CARDOZO SUAREZ', 'TÉCNICO ELECTRICISTA', 'jimena', 'suarez.julio', MD5('pass')),
  ('FABIO ANTONIO ALARCON PEREZ', 'TÉCNICO ELECTRICISTA', 'jimena', 'perez.fabio', MD5('pass')),
  ('OMAR FRANCISCO ACEVEDO MESA', 'PLANILLERO NOTIFICADOR', 'jimena', 'mesa.omar', MD5('pass')),
  ('JHONATAN DAVID CARDOZO MARTINEZ', 'PLANILLERO NOTIFICADOR', 'jimena', 'martinez.jhonatan', MD5('pass')),
  ('ALEJANDRO ACEVEDO MESA', 'COORDINADOR HSE', 'jimena', 'mesa.alejandro', MD5('pass')),
  ('YOJAN EDUARDO REYES SALINAS', 'PLANILLERO NOTIFICADOR', 'jimena', 'salinas.yojan', MD5('pass')),
  ('MILTON LEONEL SANCHEZ PEÑA', 'PLANILLERO NOTIFICADOR', 'jimena', 'pena.milton', MD5('pass')),
  ('ANDERSON FERNEY GONZALEZ COCA', 'TÉCNICO ELECTRICISTA', 'jimena', 'coca.anderson', MD5('pass')),
  ('JORGE IVAN SALAS SANTANA', 'TÉCNICO ELECTRICISTA', 'jimena', 'santana.jorge', MD5('pass')),
  ('ROBINSON JULIAN MATTA SAMACA', 'PLANILLERO NOTIFICADOR', 'jimena', 'samaca.robinson', MD5('pass')),
  ('JAIBER HOYOS SEPULVEDA', 'TÉCNICO ELECTRICISTA', 'jimena', 'sepulveda.jaiber', MD5('pass')),
  ('JUAN CAMILO GARCIA LOZANO', 'TÉCNICO ELECTRICISTA', 'jimena', 'lozano.juan', MD5('pass')),
  ('BLANCA JANETH GUZMAN TREJOS', 'COORDINADORA ADMINISTRATIVA', 'jimena', 'trejos.blanca', MD5('pass')),
  ('LEIDY JULIA ACOSTA RAMIREZ', 'AUXILIAR DE OFICINA', 'jimena', 'ramirez.leidy', MD5('pass')),
  ('ANDRES ANTONIO RENGIFO PAVA', 'PLANILLERO NOTIFICADOR', 'jimena', 'pava.andres', MD5('pass')),
  ('DAVID SANTIAGO CHAPARRO SANTOS', 'TÉCNICO ELECTRICISTA', 'jimena', 'santos.david', MD5('pass')),
  ('MARIA ROSALIA GARCIA YAGAMA', 'AUXILIAR DE OFICINA', 'jimena', 'yagama.maria', MD5('pass')),
  ('CESAR ANDRES CORONADO LASPRILLA', 'TÉCNICO ELECTRICISTA', 'jimena', 'lasprilla.cesar', MD5('pass')),
  ('JHUVER YAMIR SOLER LOPEZ', 'TÉCNICO ELECTRICISTA', 'jimena', 'lopez.jhuver', MD5('pass')),
  ('ALVARO ALSELMO PACHECO LOPEZ', 'TÉCNICO ELECTRICISTA', 'jimena', 'lopez.alvaro', MD5('pass')),
  ('PEDRO LEONEL MURCIA VILLAMIL', 'TÉCNICO ELECTRICISTA', 'jimena', 'villamil.pedro', MD5('pass')),
  ('MARIA ELENA PEREZ CORREDOR', 'COORDINADORA ZONA', 'jimena', 'corredor.maria', MD5('pass')),
  ('DERLY MARIANA DUCON GIRON', 'PLANILLERO NOTIFICADOR', 'jimena', 'giron.derly', MD5('pass')),
  ('YURY ESPERANZA LUIS HUERTAS', 'PLANILLERO NOTIFICADOR', 'jimena', 'huertas.yury', MD5('pass')),
  ('YENEMAELI PINZON RUIZ', 'PLANILLERO NOTIFICADOR', 'jimena', 'ruiz.yenemaeli', MD5('pass')),
  ('JUAN EUGENIO RODRIGUEZ MORA', 'PLANILLERO NOTIFICADOR', 'jimena', 'mora.juan', MD5('pass')),
  ('PAULA ALEJANDRA LUIS GONZALEZ', 'PLANILLERO NOTIFICADOR', 'jimena', 'gonzalez.paula', MD5('pass')),
  ('HERNAN ANDRES GARCIA RAMIREZ', 'PLANILLERO NOTIFICADOR', 'jimena', 'ramirez.hernan', MD5('pass')),
  ('WILMER ALEXANDER PEREZ CORONADO', 'TÉCNICO ELECTRICISTA', 'jimena', 'coronado.wilmer', MD5('pass')),
  ('ANDRES DAVID GUERRERO RUEDA', 'PLANILLERO NOTIFICADOR', 'jimena', 'rueda.andres', MD5('pass')),
  ('YEFERSON ROGELIO ROJAS ALFONSO', 'PLANILLERO NOTIFICADOR', 'jimena', 'alfonso.yeferson', MD5('pass')),
  ('EDWIN ALEXIS GONZALEZ PABON', 'TÉCNICO ELECTRICISTA', 'jimena', 'pabon.edwin', MD5('pass')),
  ('FANNY BEATRIZ SILVA BECERRA', 'PLANILLERO NOTIFICADOR', 'jimena', 'becerra.fanny', MD5('pass')),
  ('MAGDA CRISTINA MOGOLLON GOMEZ', 'SUPERVISOR DE CONTRATO', 'jimena', 'gomez.magda', MD5('pass')),
  ('JHON PABLO FRACICA SARMIENTO', 'TÉCNICO ELECTRICISTA', 'jimena', 'sarmiento.jhon', MD5('pass')),
  ('CLAUDIA PATRICIA DURAN CAMARGO', 'COORDINADORA ZONA', 'jimena', 'camargo.claudia', MD5('pass')),
  ('LEIDY JOHANNA PERILLA PEÑA', 'PLANILLERO NOTIFICADOR', 'jimena', 'pena.leidy', MD5('pass')),
  ('JUAN FELIPE AGUILAR SALAZAR', 'PLANILLERO NOTIFICADOR', 'jimena', 'salazar.juan', MD5('pass')),
  ('MAYRA ALEJANDRA LOZANO MURCIA', 'PLANILLERO NOTIFICADOR', 'jimena', 'murcia.mayra', MD5('pass')),
  ('NICOLAS FELIPE VARGAS FONSECA', 'TÉCNICO ELECTRICISTA', 'jimena', 'fonseca.nicolas', MD5('pass')),
  ('CAMILO ANDRES VELASCO VARGAS', 'PLANILLERO NOTIFICADOR', 'jimena', 'vargas.camilo', MD5('pass')),
  ('NHORA JIMENA GONZALEZ PEREZ', 'PROFESIONAL HSE', 'jimena', 'perez.nhora', MD5('pass')),
  ('JOHAN SEBASTIAN HERNANDEZ PINZON', 'TÉCNICO ELECTRICISTA', 'jimena', 'pinzon.johan', MD5('pass')),
  ('JEISSON CAMILO LOPEZ RODRIGUEZ', 'TÉCNICO ELECTRICISTA', 'jimena', 'rodriguez.jeisson', MD5('pass')),
  ('DEYSI YOLIMA CUEVAS MENDIVELSO', 'PLANILLERO NOTIFICADOR', 'jimena', 'mendivelso.deysi', MD5('pass')),
  ('SERGIO ANTONIO PINILLA TRIANA', 'PLANILLERO NOTIFICADOR', 'jimena', 'triana.sergio', MD5('pass')),
  ('LEIDY VIVIANA ACEVEDO SIERRA', 'PLANILLERO NOTIFICADOR', 'jimena', 'sierra.leidy', MD5('pass')),
  ('DIEGO ALEXANDER ROJAS CHAPARRO', 'APRENDIZ SENA', 'jimena', 'chaparro.diego', MD5('pass')),
  ('FABIAN HUMBERTO CARDONA RESTREPO', 'APRENDIZ SENA', 'jimena', 'restrepo.fabian', MD5('pass'));
