INSERT INTO `usuarios` (`nombres`, `cargo`, `jefe`, `usuario`, `contrasena`) VALUES
  ('AMAYA MALAGON JUAN CAMILO', 'TECNICO CONDUCTOR', 'edison', 'camilo.amaya', MD5('pass')),
  ('ARANA VELASQUEZ FREDY DAVID', 'TECNICO CONDUCTOR', 'edison', 'david.arana', MD5('pass')),
  ('AREVALO ROA JOSE DEL CARMEN', 'SUPERVISOR', 'edison', 'carmen.arevalo', MD5('pass')),
  ('ARIAS SUAREZ ASTRITH DAYANA', 'TECNICO EN FORMACION', 'edison', 'dayana.arias', MD5('pass')),
  ('AVILA LOPEZ SARIC ALEJANDRA', 'TECNICO EN FORMACION', 'edison', 'alejandra.avila', MD5('pass')),
  ('BENITEZ NIÑO RAFAEL LEONARDO', 'AUXILIAR ANALISTA DE MACROMEDICION', 'edison', 'leonardo.benitez', MD5('pass')),
  ('BOHADA VALBUENA HELVER ANTONIO', 'TECNICO EN FORMACION', 'edison', 'antonio.bohada', MD5('pass')),
  ('CARDOZO RINCON LISBET CARINA', 'TECNICO EN FORMACION', 'edison', 'carina.cardozo', MD5('pass')),
  ('CHAPARRO PEDRAZA EDISON HERNANDO', 'COORDINADOR HSE', 'edison', 'hernando.chaparro', MD5('pass')),
  ('CORREA BLANCO CAMILO ANDRES', 'ADMINISTRADOR', 'edison', 'andres.correa', MD5('pass')),
  ('CORREDOR GONZALEZ HERNAN DARIO', 'TECNICO CONDUCTOR', 'edison', 'dario.corredor', MD5('pass')),
  ('COY LOPEZ IVAN CAMILO', 'DIRECTOR OPERATIVO', 'edison', 'camilo.coy', MD5('pass')),
  ('DIAZ FRANCO ALEXANDER', 'TECNICO CONDUCTOR', 'edison', 'alexander.diaz', MD5('pass')),
  ('DIAZ GAMEZ DANIEL FELIPE', 'TECNICO EN FORMACION', 'edison', 'felipe.diaz', MD5('pass')),
  ('DUEÑAS MARTINEZ ANLLY LORENA', 'DIGITADORA', 'edison', 'lorena.duenas', MD5('pass')),
  ('FERNANDEZ DURAN JENNY CAROLINA', 'TECNICO EN FORMACION', 'edison', 'carolina.fernandez', MD5('pass')),
  ('FLECHAS HERNANDEZ MANUEL ALBERTO', 'TECNICO EN FORMACION', 'edison', 'alberto.flechas', MD5('pass')),
  ('FLOREZ MURCIA JAIR FERNANDO', 'CONDUCTOR, AUXILIAR SEMIDIRECTA', 'edison', 'fernando.florez', MD5('pass')),
  ('FONSECA MAYORDOMO ANDRES JULIAN', 'TECNICO EN FORMACION', 'edison', 'julian.fonseca', MD5('pass')),
  ('FONSECA MAYORDOMO JONATHAN DANIEL', 'TECNICO EN FORMACION', 'edison', 'daniel.fonseca', MD5('pass')),
  ('FONSECA QUIROGA GREGORIO ROLANDO', 'TECNICO CONDUCTOR', 'edison', 'rolando.fonseca', MD5('pass')),
  ('GAMEZ PEDROZA EUTINIO', 'TECNICO CONDUCTOR', 'edison', 'eutinio.gamez', MD5('pass')),
  ('GIL CASTRO LEIDY YOHANA', 'TECNICO EN FORMACION', 'edison', 'yohana.gil', MD5('pass')),
  ('GUERRERO FERNANADEZ VICTOR HUGO', 'TECNICO CONDUCTOR DE MEDIDA SEMIDIRECTA', 'edison', 'hugo.guerrero', MD5('pass')),
  ('GUTIERREZ MESA WILLIAM ALEXANDER', 'TECNICO CONDUCTOR', 'edison', 'alexander.gutierrez', MD5('pass')),
  ('GUZMAN FAGUA ELMER JOSE', 'TECNICO CONDUCTOR', 'edison', 'jose.guzman', MD5('pass')),
  ('LÓPEZ ORTIZ FRANSY RUBIELA', 'SERVICIOS GENERALES', 'edison', 'rubiela.lopez', MD5('pass')),
  ('LOPEZ PACHECO JOSE MIGUEL', 'TECNICO EN FORMACION', 'edison', 'miguel.lopez', MD5('pass')),
  ('LOPEZ PACHECO LEIDY PAOLA', 'TECNICO EN FORMACION', 'edison', 'paola.lopez', MD5('pass')),
  ('MANCIPE MANCIPE CAMPO ELIAS', 'TECNICO  INDIRECTA', 'edison', 'elias.mancipe', MD5('pass')),
  ('MANRIQUE LIZARAZO MANUEL IGNACIO', 'TECNICO CONDUCTOR', 'edison', 'ignacio.manrique', MD5('pass')),
  ('MARTINEZ CARDENAS WILSON RICHAR', 'TECNICO CONDUCTOR', 'edison', 'richar.martinez', MD5('pass')),
  ('MAYORDOMO MAYORDOMO CESAR ORLANDO', 'TECNICO CONDUCTOR', 'edison', 'orlando.mayordomo', MD5('pass')),
  ('MOLINA ROJAS JOSE DEL CARMEN', 'TECNICO CONDUCTOR', 'edison', 'carmen.molina', MD5('pass')),
  ('MOLINA VILLALOBOS CESAR ALBERTO', 'TECNICO CONDUCTOR', 'edison', 'alberto.molina', MD5('pass')),
  ('MONTAÑA RAMIREZ HENRY ANTONIO', 'TECNICO EN FORMACION', 'edison', 'antonio.montana', MD5('pass')),
  ('NARANJO MACIAS CINDY VIVIANA', 'GESTORA SOCIAL', 'edison', 'viviana.naranjo', MD5('pass')),
  ('PARADA CARVAJAL HERNAN DARIO', 'AUXILIAR OPERATIVO', 'edison', 'dario.parada', MD5('pass')),
  ('PARRA VARGAS RONALD ABEL', 'TECNICO CONDUCTOR', 'edison', 'abel.parra', MD5('pass')),
  ('PERALTA CONTRERAS HENRY', 'SUPERVISOR 2 CENTRO', 'edison', 'henry.peralta', MD5('pass')),
  ('PUERTO SANCHEZ VIVIANA ESTER', 'TECNICO EN FORMACION', 'edison', 'ester.puerto', MD5('pass')),
  ('PULIDO BELLO MARTIN HUMBERTO', 'SUPERVISOR', 'edison', 'humberto.pulido', MD5('pass')),
  ('REINA BAUTISTA MANUEL ALFONSO', 'TECNICO CONDUCTOR', 'edison', 'alfonso.reina', MD5('pass')),
  ('RICO CADENA OCTAVIO ENRIQUE', 'TECNICO CONDUCTOR', 'edison', 'enrique.rico', MD5('pass')),
  ('ROA SALCEDO WILLIAM ALFREDO', 'TECNICO CONDUCTOR', 'edison', 'alfredo.roa', MD5('pass')),
  ('ROCHA CORREDOR DIANA CAROLINA', 'COORDINADORA GESTION SOCIAL', 'edison', 'carolina.rocha', MD5('pass')),
  ('RUIZ MARTINEZ IVAN DARIO', 'TECNICO EN FORMACION', 'edison', 'dario.ruiz', MD5('pass')),
  ('SANCHEZ VELASQUEZ SANDRA MIREYA', 'TECNICO EN FORMACION', 'edison', 'mireya.sanchez', MD5('pass')),
  ('SERRANO CASTELLANOS PABLO ALEXANDER', 'TECNICO CONDUCTOR', 'edison', 'alexander.serrano', MD5('pass')),
  ('TORO PARADA FRANDINEY', 'TECNICO EN FORMACION', 'edison', 'frandiney.toro', MD5('pass')),
  ('TOVAR FONSECA MIGUEL ANGEL', 'AUXILIAR INDIRECTA', 'edison', 'angel.tovar', MD5('pass')),
  ('VALLEJO BOHORQUEZ HEIDY DAYANA', 'TECNICO EN FORMACION', 'edison', 'dayana.vallejo', MD5('pass')),
  ('VARGAS ROMERO WILMER ARNULFO', 'TECNICO CONDUCTOR', 'edison', 'arnulfo.vargas', MD5('pass')),
  ('ZARABANDA GONZALEZ EDWIN ARTURO', 'PROFESIONAL ANALISTA DE MACROMEDICION', 'edison', 'arturo.zarabanda', MD5('pass')),
  ('ZAPATA BARON JUAN ESTEBAN', 'TECNICO EN FORMACION', 'edison', 'esteban.zapata', MD5('pass'));
